#!/bin/bash
#
# GIT post-update script for the repository.
#
# This script acts upon incoming git push. It merges the incoming changes to the current branch.
#
# Author:   Fabien Bouleau
# Creation: 24-May-2013

REFS=$( echo $1 | cut -f 3- -d '/' )
EXEC=$0
[ -h "$0" ] && EXEC=$( readlink "$EXEC" )
MYDIR=$( cd `dirname $EXEC`; pwd )
APPNAME=$( basename $EXEC )
LOGDIR=$MYDIR/log

cd $MYDIR
unset GIT_DIR
log git stash -u >>$LOGDIR/$APPNAME.log
log git merge $REFS >>$LOGDIR/$APPNAME.log
log git push >>$LOGDIR/$APPNAME.log
log git stash pop >>$LOGDIR/$APPNAME.log
log git branch -d $REFS >>$LOGDIR/$APPNAME.log

